baseURL = 'https://user27c.github.io/'
# baseURL = "http://localhost:1313/"
locale = 'zh-CN'
title = "22-7's information"
theme = 'reimu'

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

# 为保证代码块的正确显示
[markup.highlight]
guessSyntax = true
noClasses = false